<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/count_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Find and Count Missing Values (Python Colab Tutorial)

## How do I quickly find NaN or missing values within a dataset?

NaN - Not a Number

Use .isna() to check for missing values using boolean indexing

In [ ]:
# import libraries
import seaborn as sns
import pandas as pd

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')
penguins.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [ ]:
# identify missing values
missing_values = penguins.isna()
missing_values.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True
9,False,False,False,False,False,False,True

In [ ]:
# count missing values by column
missing_counts = penguins.isna().sum()
print(missing_counts)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
# count total missing values
total_missing = penguins.isna().sum().sum()
print(total_missing)

19

# PLEASE LIKE & SUBSCRIBE FOR MORE VIDEOS