<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/drop_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Drop Columns in Pandas (Python Colab Tutorial)

## Dropping Columns

Dropping entire columns at once

Dublicates, useless columns, sensitive information

Clean and efficient

Drop one or multiple columns at once

.drop()

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Drop a Single Column

In [ ]:
# drop the island column
penguins_no_island = penguins.drop(columns='island')
penguins_no_island.head()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,39.1,18.7,181.0,3750.0,Male
1,Adelie,39.5,17.4,186.0,3800.0,Female
2,Adelie,40.3,18.0,195.0,3250.0,Female
3,Adelie,NaN,NaN,NaN,NaN,NaN
4,Adelie,36.7,19.3,193.0,3450.0,Female

In [ ]:
# drop the body mass column
penguins_no_mass = penguins.drop(columns='body_mass_g')
penguins_no_mass.head()

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm     sex
0  Adelie  Torgersen            39.1           18.7              181.0    Male
1  Adelie  Torgersen            39.5           17.4              186.0  Female
2  Adelie  Torgersen            40.3           18.0              195.0  Female
3  Adelie  Torgersen             NaN            NaN                NaN     NaN
4  Adelie  Torgersen            36.7           19.3              193.0  Female

## Drop Multiple Columns

In [ ]:
# drop measurement columns
penguins_no_measurements_ = penguins.drop(columns=['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g'])
penguins_no_measurements_.head()

  species     island     sex
0  Adelie  Torgersen    Male
1  Adelie  Torgersen  Female
2  Adelie  Torgersen  Female
3  Adelie  Torgersen     NaN
4  Adelie  Torgersen  Female

In [ ]:
# drop measurement columns with a list
measurement_cols = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']

penguins_no_measurements = penguins.drop(columns=measurement_cols)
penguins_no_measurements.head()

  species     island     sex
0  Adelie  Torgersen    Male
1  Adelie  Torgersen  Female
2  Adelie  Torgersen  Female
3  Adelie  Torgersen     NaN
4  Adelie  Torgersen  Female

# PLEASE LIKE & SUBSCRIBE FOR MORE VIDEOS