<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/series_vs_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Series vs. Dataframe (Python Colab Tutorial)

## Series vs. Dataframe

Series = 1D array (single row or column)

Dataframe = 2D table (rows and columns)

In [ ]:
# import libraries
import pandas as pd

## Let's look at a series.

In [ ]:
# create a series
penguin_species = pd.Series(['Adelie', 'Chinstrap', 'Gentoo'], name='species')
penguin_species

0       Adelie
1    Chinstrap
2       Gentoo
Name: species, dtype: object

In [ ]:
# check data type
type(penguin_species)

pandas.core.series.Series

## Let's look at a dataframe.

In [ ]:
# create a table
penguin_data = {
    'Name': ['John', 'Paul', 'George', 'Ringo'],
    'Species': ['Adelie', 'Adelie', 'Gentoo', 'Chinstrap'],
    'Age': [5, 5, 7, 4]
}

# create a dataframe from table
penguins = pd.DataFrame(penguin_data)
penguins

     Name    Species  Age
0    John     Adelie    5
1    Paul     Adelie    5
2  George     Gentoo    7
3   Ringo  Chinstrap    4

In [ ]:
# check data type
type(penguins)

pandas.core.frame.DataFrame

# PLEASE LIKE & SUBSCRIBE FOR MORE VIDEOS